# Generated by Django 2.2.6 on 2020-06-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admindb',
            name='image',
            field=models.ImageField(default='', upload_to='image'),
        ),
    ]
